# action.yml
name: 'wait-action'
description: 'Simple action allowing to wait until some jobs done'
inputs:
  head-sha:
    description: 'Commit hash for waiting on'
    required: true
  poll-delay:
    descripton: 'Delay between poll requests to Github API'
    required: true
    default: '10s'
  workflows:
    description: 'Workflows wait conditions'
    required: true
    default: ''
  debug:
    descriptor: 'Flag for displaying debug logs'
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
